export type Lang = 'es' | 'en'

/** Diccionario maestro. `es` define la forma; `en` debe cumplirla. */
const es = {
  nav: {
    home: 'Inicio',
    projects: 'Proyectos',
    store: 'Tienda',
    about: 'Nosotros',
    admin: 'Admin',
    login: 'Iniciar sesión',
    openMenu: 'Abrir menú',
    closeMenu: 'Cerrar menú',
  },
  theme: {
    toDark: 'Cambiar a modo oscuro',
    toLight: 'Cambiar a modo claro',
  },
  lang: { toEn: 'Switch to English', toEs: 'Cambiar a español' },
  hero: {
    title: 'Buenos, rápidos y desesperados por trabajar.',
    lead: 'Webs, apps y bots a medida por un equipo que responde en horas, no en semanas.',
    ctaPrimary: 'Empezar mi proyecto',
    ctaSecondary: 'Ver proyectos',
    stackLine: 'TypeScript · React · Node.js · Python · PostgreSQL · Discord.js',
  },
  home: {
    servicesLabel: '~/servicios',
    servicesTitle: 'Dos cosas, hechas bien',
    servicesMore: 'Ver la tienda',
    whyLabel: '~/por-qué-nosotros',
    whyTitle: 'Por qué nosotros',
    whyPoints: [
      { title: 'Hablas con quien programa', body: 'Cero intermediarios.' },
      { title: 'Respuesta en horas', body: 'Vivimos en Discord y el email.' },
      { title: 'Nivel sin precio de agencia', body: 'Código documentado y tuyo.' },
    ],
    faqLabel: '~/faq',
    faqTitle: 'Lo que todos preguntan',
    faq: {
      items: [
        {
          q: '¿Cuánto tarda un proyecto?',
          a: 'Una landing: 5 a 10 días. Una web completa o un bot: 2 a 4 semanas. Fecha estimada antes de empezar, y se cumple.',
        },
        {
          q: '¿Cómo funcionan los pagos?',
          a: '50% para arrancar, 50% al entregar. Transferencia, PayPal o cripto.',
        },
        {
          q: '¿El código es mío?',
          a: 'Sí. Repositorio completo con documentación. Sin candados.',
        },
        {
          q: '¿Y si me arrepiento?',
          a: 'El anticipo cubre el trabajo hasta ese punto; no sigues debiendo nada más.',
        },
        {
          q: '¿Por qué “desempleados”?',
          a: 'Empezamos el equipo entre trabajos y lo abrazamos: sin jefes ni reuniones inútiles, con todo el tiempo para tu proyecto.',
        },
      ],
    },
    communityLabel: '~/comunidad',
    communityTitle: 'Espía el taller',
    communityLead: 'Construimos en público. Entra, pregunta o solo mira.',
    discordCta: 'Entrar al Discord',
    discordNote: 'Avances, dudas y demos en vivo.',
    githubCta: 'Ver el código',
    githubNote: 'Todo nuestro trabajo, en repositorios abiertos.',
    specialtyLabel: '~/especialidad (en definición)',
    specialtyPlaceholders: ['Especialidad A', 'Especialidad B', 'Especialidad C'],
  },
  projectsPage: {
    label: '~/proyectos',
    title: 'Lo que construimos',
    lead: 'Proyectos propios: lo que hacemos cuando nadie nos paga es la mejor prueba de lo que sabemos hacer.',
    ctaCode: 'Ver en GitHub',
    ctaDemo: 'Ver demo',
    comingSoon: 'Repo próximamente',
    statuses: { live: 'activo', beta: 'beta', wip: 'en desarrollo' } as Record<string, string>,
    more: 'Todo el código en GitHub',
  },
  store: {
    label: '~/tienda',
    title: 'Tienda',
    lead: 'Precios fijos, alcance cerrado. Elige, reserva tu lugar y coordinamos el resto por Discord el mismo día.',
    from: 'desde',
    quote: 'a cotizar',
    quoteCta: 'Cuéntame qué necesitas',
    add: 'Añadir al carrito',
    added: 'En el carrito',
    monthly: '/mes',
    cartTitle: 'Tu carrito',
    cartEmpty: 'Vacío. Añade un servicio para empezar.',
    total: 'Total',
    checkout: 'Reservar mi lugar',
    checkoutSignIn: 'Inicia sesión para reservar',
    success: '¡Orden creada! Te contactamos hoy por Discord o email para coordinar el pago y arrancar.',
    orderPlaced: 'Orden',
    fine: '50% ahora, 50% al entregar. Coordinamos el pago por Discord o email — todavía sin pasarela automática.',
  },
  aboutPage: {
    label: '~/nosotros',
    title: 'Quiénes somos',
    lead: 'Tres devs, cero gerentes. Cada uno responde por su área y todos por el resultado.',
    photoAlt: 'Foto de',
    photoPending: 'Foto',
    github: 'GitHub',
    githubPending: 'Perfil próximamente',
  },
  admin: {
    label: '~/admin',
    title: 'Panel de administradores',
    lead: 'Proyectos, ventas y consola. Solo para el equipo.',
    locked: 'Acceso restringido',
    lockedBody: 'Esta área es del equipo. Si eres parte, inicia sesión con tu cuenta de administrador.',
    signIn: 'Iniciar sesión como admin',
    metrics: {
      revenue: 'Ingresos confirmados',
      pending: 'Órdenes pendientes',
      projects: 'Proyectos',
      products: 'Productos en tienda',
    },
    tabs: { console: 'Consola', projects: 'Proyectos', sales: 'Ventas' },
    salesState: { paid: 'pagada', pending: 'pendiente' } as Record<string, string>,
    markPaid: 'Marcar pagada',
    remove: 'Quitar',
    emptySales: 'Sin órdenes todavía.',
    consoleWelcome: 'desempleados CLI · escribe "help" para ver comandos',
    notFound: 'orden no encontrada',
    removed: 'eliminado',
    prompt: 'admin@desempleados.dev',
  },
  loginPage: {
    title: 'Sistema de Login',
    lead: 'Para comprar en la tienda, seguir tus órdenes o entrar al panel.',
  },
  footer: {
    ctaLabel: '~/empezar',
    ctaTitle: '¿Tenés un proyecto en mente?',
    ctaButton: 'Ver la tienda',
    tagline: 'Hecho sin empleos, con café.',
    contact: 'Contacto',
    follow: 'Síguenos',
    sections: 'Secciones',
    account: 'Cuenta',
    loginLink: 'Sistema de Login',
    registerLink: 'Crear cuenta',
    rights: 'Todos los derechos reservados (los pocos que quedan).',
  },
}

type Dict = typeof es

const en: Dict = {
  nav: {
    home: 'Home',
    projects: 'Projects',
    store: 'Store',
    about: 'About us',
    admin: 'Admin',
    login: 'Sign in',
    openMenu: 'Open menu',
    closeMenu: 'Close menu',
  },
  theme: {
    toDark: 'Switch to dark mode',
    toLight: 'Switch to light mode',
  },
  lang: { toEn: 'Switch to English', toEs: 'Cambiar a español' },
  hero: {
    title: 'Good, fast, and desperate to work.',
    lead: 'Custom websites, apps and bots from a team that answers in hours, not weeks.',
    ctaPrimary: 'Start my project',
    ctaSecondary: 'See projects',
    stackLine: 'TypeScript · React · Node.js · Python · PostgreSQL · Discord.js',
  },
  home: {
    servicesLabel: '~/services',
    servicesTitle: 'Two things, done well',
    servicesMore: 'Visit the store',
    whyLabel: '~/why-us',
    whyTitle: 'Why us',
    whyPoints: [
      { title: 'You talk to the coder', body: 'Zero middlemen.' },
      { title: 'Answers in hours', body: 'We live on Discord and email.' },
      { title: 'Senior quality, no agency price', body: 'Documented code, and it is yours.' },
    ],
    faqLabel: '~/faq',
    faqTitle: 'What everyone asks',
    faq: {
      items: [
        {
          q: 'How long does a project take?',
          a: 'A landing: 5 to 10 days. A full site or a bot: 2 to 4 weeks. Estimated date before we start, and we keep it.',
        },
        {
          q: 'How do payments work?',
          a: '50% to start, 50% on delivery. Bank transfer, PayPal or crypto.',
        },
        {
          q: 'Do I own the code?',
          a: 'Yes. Full repository with documentation. No locks.',
        },
        {
          q: 'What if I change my mind?',
          a: 'The upfront payment covers work done so far; you owe nothing else.',
        },
        {
          q: 'Why “unemployed”?',
          a: 'We started this team between jobs and owned it: no bosses, no pointless meetings, all the time for your project.',
        },
      ],
    },
    communityLabel: '~/community',
    communityTitle: 'Watch the workshop',
    communityLead: 'We build in public. Join, ask, or just lurk.',
    discordCta: 'Join the Discord',
    discordNote: 'Progress, questions and live demos.',
    githubCta: 'Read the code',
    githubNote: 'All our work, in open repositories.',
    specialtyLabel: '~/specialty (TBD)',
    specialtyPlaceholders: ['Specialty A', 'Specialty B', 'Specialty C'],
  },
  projectsPage: {
    label: '~/projects',
    title: 'What we build',
    lead: 'Our own projects: what we make when nobody pays us is the best proof of what we can do for you.',
    ctaCode: 'View on GitHub',
    ctaDemo: 'Live demo',
    comingSoon: 'Repo coming soon',
    statuses: { live: 'live', beta: 'beta', wip: 'in development' } as Record<string, string>,
    more: 'All the code on GitHub',
  },
  store: {
    label: '~/store',
    title: 'Store',
    lead: 'Fixed prices, closed scope. Pick one, reserve your spot, and we coordinate the rest on Discord the same day.',
    from: 'from',
    quote: 'quoted',
    quoteCta: 'Tell us what you need',
    add: 'Add to cart',
    added: 'In cart',
    monthly: '/mo',
    cartTitle: 'Your cart',
    cartEmpty: 'Empty. Add a service to get started.',
    total: 'Total',
    checkout: 'Reserve my spot',
    checkoutSignIn: 'Sign in to reserve',
    success: 'Order placed! We reach out today via Discord or email to coordinate payment and kick off.',
    orderPlaced: 'Order',
    fine: '50% now, 50% on delivery. We coordinate payment over Discord or email — no automatic payment gateway yet.',
  },
  aboutPage: {
    label: '~/about',
    title: 'Who we are',
    lead: 'Three devs, zero managers. Each of us owns an area; all of us own the result.',
    photoAlt: 'Photo of',
    photoPending: 'Photo',
    github: 'GitHub',
    githubPending: 'Profile coming soon',
  },
  admin: {
    label: '~/admin',
    title: 'Admin panel',
    lead: 'Projects, sales and console. Team only.',
    locked: 'Restricted access',
    lockedBody: 'This area belongs to the team. If you are part of it, sign in with your admin account.',
    signIn: 'Sign in as admin',
    metrics: {
      revenue: 'Confirmed revenue',
      pending: 'Pending orders',
      projects: 'Projects',
      products: 'Products in store',
    },
    tabs: { console: 'Console', projects: 'Projects', sales: 'Sales' },
    salesState: { paid: 'paid', pending: 'pending' } as Record<string, string>,
    markPaid: 'Mark as paid',
    remove: 'Remove',
    emptySales: 'No orders yet.',
    consoleWelcome: 'desempleados CLI · type "help" for commands',
    notFound: 'order not found',
    removed: 'removed',
    prompt: 'admin@desempleados.dev',
  },
  loginPage: {
    title: 'Login',
    lead: 'To buy from the store, track your orders or enter the admin panel.',
  },
  footer: {
    ctaLabel: '~/start',
    ctaTitle: 'Got a project in mind?',
    ctaButton: 'Visit the store',
    tagline: 'Built without jobs, fueled by coffee.',
    contact: 'Contact',
    follow: 'Follow us',
    sections: 'Sections',
    account: 'Account',
    loginLink: 'Login',
    registerLink: 'Create account',
    rights: 'All rights reserved (the few we had left).',
  },
}

export const dict: Record<Lang, Dict> = { es, en }
export type { Dict }
